[project]
name = "optimal-quad-control-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "H S Helson Go", email = "hellston20a@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
  "gymnasium>=1.2.3",
  "hydra-core>=1.3.2",
  "jinja2>=3.1.6",
  "matplotlib>=3.10.8",
  "nn_controller",
  "numpy>=2.4.2",
  "opencv-python>=4.13.0.92",
  "pydantic>=2.12.5",
  "rerun-sdk>=0.22",
  "rich>=14.3.3",
  "scipy>=1.17.1",
  "stable-baselines3>=2.7.1",
  "tensorboard>=2.20.0",
  "torch>=2.10.0",
  "tqdm>=4.67.3",
]

[project.scripts]
optimal-quad-control-rl = "optimal_quad_control_rl:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
nn_controller = { path = "nn_controller", editable = true }

[tool.pytest.ini_options]
pythonpath = ["."]

[dependency-groups]
dev = [
    "maturin>=1.4,<2.0",
    "pytest>=9.0.2",
]
